extern cgraph_size_t FUNCTION(NAME, hash)(const void *cthis);
extern cgraph_boolean_t FUNCTION(NAME, test)(const void *cthis);
extern cgraph_boolean_t FUNCTION(NAME, equal)(const void *x, const void *y);
extern cgraph_boolean_t FUNCTION(NAME, isnan)(const TYPE x);
extern cgraph_boolean_t FUNCTION(NAME, isinf)(const TYPE x);
extern cgraph_boolean_t FUNCTION(NAME, ispinf)(const TYPE x);
extern cgraph_boolean_t FUNCTION(NAME, isninf)(const TYPE x);
extern cgraph_boolean_t FUNCTION(NAME, iszero)(const TYPE x);
extern cgraph_boolean_t FUNCTION(NAME, ismax)(const TYPE x);
extern cgraph_boolean_t FUNCTION(NAME, ismin)(const TYPE x);